'''
Problem 2 - Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the two previous terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def fib (i):
    if i == 1:
        return 1
    if i == 2:
        return 2
    return fib(i-1) + fib(i-2)

sum = 0
i = 2
while (fib(i) <= 4e6):
    sum += fib(i)
    i += 3 # fib numbers are even every third number after 2 - fib2 = 2, fib5 = 8, each even followed by two odd fibs

print(sum)

# Answer: 4,613,732
